### ISSUE TITLE
Program crashes when WPA password cracked

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#1]
```
What steps will reproduce the problem?
1. cracking WPA password.

What is the expected output? What do you see instead?

[0:00:00] started cracking WPA key for "AP"; using common-2.txt (817 passwords)
[0:00:02] cracking; 117.32 k/s; 156 keys total; 19% eta: 0:00:05
[0:00:02] cracked "AP"! the key is: "password"
Traceback (most recent call last):
  File "./wifite.py", line 2708, in <module>
    main() # launch the main method
  File "./wifite.py", line 714, in main
    wpa_crack(i)
  File "./wifite.py", line 1344, in wpa_crack
    CRACKED += 1
UnboundLocalError: local variable 'CRACKED' referenced before assignment

What version of the product are you using? On what operating system?

BT4

Please provide any additional information below.


```

Original issue reported on code.google.com by `ian.pa...@gmail.com` on 23 Sep 2010 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
That was a huge bug, easy to fix.  Thanks for the report and copy/pasted error 
dump!

Made changes to revision 16, hopefully the bug is gone forever.

Try
./wifite.py -upgrade
to automatically upgrade to the latest revision.
```

Original comment by `der...@gmail.com` on 23 Sep 2010 at 10:01
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `der...@gmail.com` on 28 Sep 2010 at 6:40
- Changed state: **Verified**
