### ISSUE TITLE
wifite not running , two different errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#114]
```


I am running Backtrack 5 R2? 
What version of the wifite are you using?
 this one : https://raw.github.com/derv82/wifite/master/wifite.py

I have two python installation , i get a different error each time

root@bt:~# python wifite.py
Traceback (most recent call last):
  File "wifite.py", line 90, in <module>
    import argparse # arg parsing
ImportError: No module named argparse
root@bt:~# python3.2 wifite.py
  File "wifite.py", line 228
    print R+' [!]'+O+' ERROR:'+G+' wifite'+O+' must be run as '+R+'root'+W
          ^
SyntaxError: invalid syntax



any suggestions?
```

Original issue reported on code.google.com by `mrlinu...@gmail.com` on 15 Feb 2013 at 7:36

**Comment by GoogleCodeExporter** [comment]
```
I know, this is old, but for some people this error may occur, when they have 
python3 installed. You have to use python2: "sudo python2 wifite.py"

btw: same error as #80
```

Original comment by `fakeat0...@gmail.com` on 8 Apr 2013 at 9:07

**Comment by GoogleCodeExporter** [comment]
```
that solved my problem, thanks!
```

Original comment by `antha...@gmail.com` on 7 Nov 2013 at 9:15
