### ISSUE TITLE
Wifite.py R34 gui issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#13]
```
What steps will reproduce the problem?
1. Upgraded to latest rev.
2. Launched ./wifite.py
3. Got errors

What is the expected output? What do you see instead?
Launch gui

[+] launching gui interface
Traceback (most recent call last):
  File "./wifite.py", line 3016, in <module>
    main() # launch the main method
  File "./wifite.py", line 723, in main
    app = App(root)
  File "./wifite.py", line 247, in __init__
    w=apply(OptionMenu, (frame, self.iface) + tuple(lst))
TypeError: __init__() takes at least 4 arguments (3 given)


What version of the product are you using? On what operating system?

r34 
Please provide any additional information below.


```

Original issue reported on code.google.com by `ondro...@gmail.com` on 27 Sep 2010 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
Scratch that I didn't have my usb wifi in so that was what was causing my issues
```

Original comment by `ondro...@gmail.com` on 27 Sep 2010 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
Thanks for posting this anyway; the program should not crash if there are no 
wireless interfaces found.

I [hopefully] fixed this bug in the revision 35.  If it's possible, could you 
please test this latest version by loading wifite without your USB adapter 
plugged in? It is supposed to not crash. (I can't easily remove the built-in 
wifi adapter on my laptop, otherwise I would test it myself).
```

Original comment by `der...@gmail.com` on 27 Sep 2010 at 3:16
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Sure no problem I will test it for you :-)
```

Original comment by `ondro...@gmail.com` on 27 Sep 2010 at 1:27

**Comment by GoogleCodeExporter** [comment]
```
Same issue with r39

raceback (most recent call last):
  File "./wifite.py", line 3074, in <module>
    main() # launch the main method
  File "./wifite.py", line 764, in main
    app = App(root)
  File "./wifite.py", line 250, in __init__
    w=apply(OptionMenu, (frame, self.iface) + tuple(lst))
TypeError: __init__() takes at least 4 arguments (3 given)

```

Original comment by `ondro...@gmail.com` on 27 Sep 2010 at 1:30

**Comment by GoogleCodeExporter** [comment]
```
i can confirm that without USB wifi adapter, the WiFite doesn't load (double 
click), when used the command python wifite.py i got exactly the above error 
message...
```

Original comment by `macris.a...@gmail.com` on 27 Sep 2010 at 1:52

**Comment by GoogleCodeExporter** [comment]
```
Issue 15 has been merged into this issue.
```

Original comment by `der...@gmail.com` on 27 Sep 2010 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
Yikes, I didn't fix this at all before.  Sorry guys.

Tested and working (for me) in revision 40.
```

Original comment by `der...@gmail.com` on 27 Sep 2010 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
I too can confirm that it is not working correctly for me as well with Rev 40
```

Original comment by `ondro...@gmail.com` on 27 Sep 2010 at 7:46

**Comment by GoogleCodeExporter** [comment]
```
Okay.

I attempted fix the bug in Revision 41: wfiite outputs the list of wireless 
devices before loading the GUI.

If the program still crashes, please copy/paste the error dump here so I can 
pinpoint where the problem lies.
```

Original comment by `der...@gmail.com` on 27 Sep 2010 at 7:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `der...@gmail.com` on 28 Sep 2010 at 6:47
- Changed state: **Fixed**
