### ISSUE TITLE
Possible Bug in wpa_crack() function call

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#141]
```
Bug Location:
 Wifite v2.0 (r86)
 line #1326       --> wpa_crack(cap)

Traceback (most recent call last):
  File "./wifite.py", line 3108, in <module>
    engine.Start()
  File "./wifite.py", line 1326, in Start
    wpa_crack(cap)
TypeError: wpa_crack() takes exactly 2 arguments (1 given)

OS: BackBox 3.13 (x86)
OS-info: Linux version 3.11.0-22-generic (buildd@lamiak) (gcc version 4.6.3 
(Ubuntu/Linaro 4.6.3-1ubuntu5) ) #38~precise1-Ubuntu SMP Fri May 16 20:50:12 
UTC 2014

Extra Info:
I've disabled wpa handshake check using tshark within the script, make the 
config line looks like "self.WPA_HANDSHAKE_TSHARK   = False".
I must do this 'cause WiFite has never been able to capture wpa handshake.


```

Original issue reported on code.google.com by `danieleb...@gmail.com` on 9 Jun 2014 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
After a few test, i found a "solution" 

- At line #1326, change the function call and add "RUN_CONFIG" as second 
argument.
  So if before it looks like 
                             --->  "wpa_crack(cap)" 
  now it should be like
                             --->  "wpa_crack(cap,RUN_CONFIG)"

- Now the bug should be avoid when starting the wpa cracking part, but for some 
reasons WiFite doesn't use the "-dict" argument from command line. So, if you 
want to use your word list, go to line #175 and modify the 
"self.WPA_DICTIONARY" path to poit to your file (i.e. In my case the entire 
line is "self.WPA_DICTIONARY       = 
'/opt/backbox/msf/data/john/wordlists/password.lst' )


Hope to be helpfull for someone
```

Original comment by `danieleb...@gmail.com` on 9 Jun 2014 at 10:13
