### ISSUE TITLE
Problem launching wifite

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#15]
```
  .;'                     `;,
 .;'  ,;'             `;,  `;,   WiFite r39
.;'  ,;'  ,;'     `;,  `;,  `;,
::   ::   :   ( )   :   ::   ::  mass WEP/WPA cracker
':.  ':.  ':. /_\ ,:'  ,:'  ,:'
 ':.  ':.    /___\    ,:'  ,:'   designed for backtrack4
  ':.       /_____\      ,:'
           /       \

[+] launching gui interface
Traceback (most recent call last):
  File "./wifite_r39.py", line 3074, in <module>
    main() # launch the main method
  File "./wifite_r39.py", line 764, in main
    app = App(root)
  File "./wifite_r39.py", line 250, in __init__
    w=apply(OptionMenu, (frame, self.iface) + tuple(lst))
TypeError: __init__() takes at least 4 arguments (3 given)

any help?
am using backtrack4 r1 in vmware
```

Original issue reported on code.google.com by `hishamth...@gmail.com` on 27 Sep 2010 at 12:26
- Merged into: #13

**Comment by GoogleCodeExporter** [comment]
```
btw, no wifi card was in
```

Original comment by `hishamth...@gmail.com` on 27 Sep 2010 at 12:29

**Comment by GoogleCodeExporter** [comment]
```
This issue is the same as issue 13. The bug was fixed in Revision 40.
```

Original comment by `der...@gmail.com` on 27 Sep 2010 at 5:47
- Changed state: **Duplicate**
