### ISSUE TITLE
Exception OSError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#35]
```
What steps will reproduce the problem?
./wifite.py -i wlan0 -nowpa -all -d none -wepw 10 -wpaw 5 -f -anon -pps 500

What is the expected output? What do you see instead?
...
[+] searching for devices in monitor mode...
[!] no wireless interfaces are in monitor mode!
[+] putting "wlan0" into monitor mode...
[+] searching for devices in monitor mode...
[+] defaulting to interface "mon0"

[+] intel4965 chipset detected

[+] waiting 1 seconds for targets to appear. press Ctrl+C to skip the wait      


[0:00:31] 3 targets and 1 clients found 
[+] targeting: * 

[+] estimated maximum wait time is 2 hours, 00 minutes
[+] changing mac address to *...  changed!

[+] attacking *...
[+] killing airodump-ng
[+] stopping mon0
[0:09:58] attempting intel 4965 workaround
[+] executing command: wpa_supplicant -cfake.conf -iwlan0 -Dwext -dd
[+] 30-second timeout starting now...
[+] did not receive State: ASSOCIATED -> COMPLETED
Traceback (most recent call last):
  File "./wifite.py", line 3222, in <module>
    main() # launch the main method
  File "./wifite.py", line 906, in main
    attack(x - 1) # subtract one because arrays start at 0
  File "./wifite.py", line 1755, in attack
    attack_wep_all(index)
  File "./wifite.py", line 1853, in attack_wep_all
    faked=attack_fakeauth_intel(index)
  File "./wifite.py", line 2433, in attack_fakeauth_intel
    proc_intel.close(force=True)
  File "/usr/lib/python2.6/dist-packages/pexpect.py", line 666, in close
    raise ExceptionPexpect ('close() could not terminate the child using terminate()')
pexpect.ExceptionPexpect: close() could not terminate the child using 
terminate()
Exception OSError: OSError(9, 'Bad file descriptor') in <bound method 
spawn.__del__ of <pexpect.spawn object at 0x134b690>> ignored


What version of the product are you using? On what operating system?
r60
[+] your copy of wifite.py is up to date

Ubuntu 10.04.1 LTS 64-Bit, python 2.6.5

Please provide any additional information below.


```

Original issue reported on code.google.com by `thorsten...@gmail.com` on 14 Jan 2011 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
I tried to write a work-around for the Intel 4965 chipset.  When I wrote 
wifite, the 4965 chipset was not able to fake-authenticate using aireplay-ng 
(-1), so I wrote a small method that used wpa_supplicant and a fake .conf file 
to fake-authenticate with the access point.  

The testers claimed that the script worked with the intel 4965 chipset in 
Backtrack 4.  My guess is that Ubuntu 10.04 does (or doesn't do) something that 
Backtrack 4 does -- perhaps the drivers are different, or ... hmm...

I can try to write a fix so that the program does not crash when 
fake-authentication fails. However, this means that fake-authentication will 
still fail, so maybe you aren't close enough to the router...

If you ARE close enough, maybe it's just a problem with Ubuntu 10.04 since the 
script apparently works for BT4.  I don't want to 
code-upload-troubleshoot-repeat for a chipset I have no access to (it's a big 
headache for me).  The only fix I can offer is that the program won't crash 
completely...

In the mean time, you could boot into a Backtrack4 Live CD/DVD/USB and use that 
operating system (since wifite was designed for BT4), try different wireless 
drivers (probably won't help) or try a different wireless device (the ALFA 
awus036h is amazing and ~$30).

Sorry, this probably isn't what you wanted to hear. 
I'll post a link if I [may have] fixed it.
```

Original comment by `der...@gmail.com` on 15 Jan 2011 at 3:10
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Just committed r62. I tried to catch all exceptions, including the Pexpect and 
OSError.
Hopefully the new version doesn't crap out on you...

python wifite.py -update
```

Original comment by `der...@gmail.com` on 15 Jan 2011 at 3:43
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

first, thank you for the fast response. Very good :)

I updated to r62 and now I get a "new" error. It looks like the script hangs at 
the 2nd attempt.


[+] 30-second timeout starting now...
[+] did not receive State: ASSOCIATED -> COMPLETED
[+] received ExceptionPexpect
[!]        wpa_supplicant workaround failed!

[+] starting wlan1 on channel 1
[+] starting airodump-ng
[0:09:26] fake authentication unsuccessful :(       
[0:09:26] continuing attack anyway (odds of success are low)
[0:09:59] started arp replay attack on "*"; Ctrl+C for options
[0:09:59] arp replay attack on "*" captured 0 ivs (0/sec)                  
[0:09:54] arp replay attack failed

[0:09:59] started chop-chop attack on "*"; Ctrl+C for options
[0:09:59] chop-chop attack on "*" captured 0 ivs (0/sec)                  
[0:09:54] attack failed; unable to generate keystream

[0:09:59] started fragmentation attack on "*"; Ctrl+C for options
[0:09:59] fragmentation attack on "*" captured 0 ivs (0/sec)                  
[0:09:54] attack failed; unable to generate keystream

[0:09:59] started -p0841 attack on "*"; Ctrl+C for options
[0:09:59] -p0841 attack on "*" captured 0 ivs (0/sec)                  
[0:09:54] -p0841 attack failed

[+] attack unsuccessful! unable to generate enough IVS in time

[+] attacking "*"...
[+] killing airodump-ng
[+] stopping mon0
[0:09:58] attempting intel 4965 workaround
[+] executing command: wpa_supplicant -cfake.conf -iwlan0 -Dwext -dd
[+] 30-second timeout starting now...
Traceback (most recent call last):
  File "./wifite.py", line 3228, in <module>
    main() # launch the main method
  File "./wifite.py", line 906, in main
    attack(x - 1) # subtract one because arrays start at 0
  File "./wifite.py", line 1755, in attack
    attack_wep_all(index)
  File "./wifite.py", line 1853, in attack_wep_all
    faked=attack_fakeauth_intel(index)
  File "./wifite.py", line 2427, in attack_fakeauth_intel
    proc_intel.expect('State: ASSOCIATED -> COMPLETED', timeout=30)
  File "/usr/lib/python2.6/dist-packages/pexpect.py", line 1311, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/usr/lib/python2.6/dist-packages/pexpect.py", line 1325, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/usr/lib/python2.6/dist-packages/pexpect.py", line 1378, in expect_loop
    c = self.read_nonblocking (self.maxread, timeout)
  File "/usr/lib/python2.6/dist-packages/pexpect.py", line 803, in read_nonblocking
    r,w,e = self.__select([self.child_fd], [], [], 0) # timeout of 0 means "poll"
  File "/usr/lib/python2.6/dist-packages/pexpect.py", line 1549, in __select
    return select.select (iwtd, owtd, ewtd, timeout)
select.error: (9, 'Bad file descriptor')
Exception OSError: OSError(9, 'Bad file descriptor') in <bound method 
spawn.__del__ of <pexpect.spawn object at 0x1111590>> ignored


```

Original comment by `thorsten...@gmail.com` on 16 Jan 2011 at 9:33

**Comment by GoogleCodeExporter** [comment]
```
Yikes, that looks like a different bug in the same area. I'll look at it later.

Thanks for replying. You don't need to start new issues: I can see whenever a 
new comment is posted -- I just haven't had time to check recently.
```

Original comment by `der...@gmail.com` on 18 Jan 2011 at 6:39
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Ok.  I added more error-handling and committed r63. Hopefully this will stop 
the error :\

I really hate debugging for hardware I don't have.  If I had a iwl4965, this 
would've been done long ago and I wouldn't have to waste your time >;[
```

Original comment by `der...@gmail.com` on 19 Jan 2011 at 3:12

**Comment by GoogleCodeExporter** [comment]
```
Hi,
I think I have a similar problem.
When I trie to work with a WEP encrypted network I have a issue with pexpect.
Pexpect need python but only on 2.5 and I'm on 2.5 so it don't whant to be 
installed and I can't start WEP cracking.
```

Original comment by `Miasm...@gmail.com` on 13 Apr 2011 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
I get this error in Backtrack 5.
```

Original comment by `Michael....@gmail.com` on 4 Sep 2011 at 2:33

**Comment by GoogleCodeExporter** [comment]
```
On the latest revision the wpa_supplicant workaround doesn't exist  , can yu 
please re add it 
```

Original comment by `ZzeC...@gmail.com` on 22 Jul 2012 at 6:37
