### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#46]
```
My apologies if this is a newbie question, but wifite has started throwing up 
the following error whenever I attempt to launch it:

(Running BC4 R2)

root@bt:~# python wifite.py

  .;'                     `;,
 .;'  ,;'             `;,  `;,   WiFite r78
.;'  ,;'  ,;'     `;,  `;,  `;,
::   ::   :   ( )   :   ::   ::  mass WEP/WPA cracker
':.  ':.  ':. /_\ ,:'  ,:'  ,:'
 ':.  ':.    /___\    ,:'  ,:'   designed for backtrack4
  ':.       /_____\      ,:'
           /       \

[+] launching gui interface
[+] wireless devices: "wlan0  Intel 4965/5xxx iwlagn - [phy0]"
Traceback (most recent call last):
  File "wifite.py", line 3542, in <module>
    main() # launch the main method
  File "wifite.py", line 833, in main
    app = App(root)
  File "wifite.py", line 275, in __init__
    updatesqlstatus('[+] wireless devices: "' + ', '.join(lst) +'"')
  File "wifite.py", line 1382, in updatesqlstatus
    db.execute("INSERT INTO status (timestamp, status) VALUES (%i, '%s')" % (time.time(), text))
sqlite3.OperationalError: unable to open database file
root@bt:~#                                             


This happened upon reboot where previously I've had no issues.
Any help would be greatly apreciated!
```

Original issue reported on code.google.com by `Kirill.K...@gmail.com` on 9 May 2011 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
The error is that the script can't open the log.db file.  Does it(log.db) exist 
before the script ran, what about after? What are its permissions like?

Wifite is coded to create the file if it doesn't exist, so this unable to open 
error makes me thing that the file exists, but has the wrong permissions
```

Original comment by `bettse@gmail.com` on 9 May 2011 at 10:33

**Comment by GoogleCodeExporter** [comment]
```
The file does exist and the permissions are set to both read and write in the 
GUI interface by right clicking as well as running the command chmod 0777 
log.db and for the root directory? I have tried deleting the file as well and 
same thing...

I have had wifite running perfectly, but after a reboot it suddenly started 
throwing up this error. If I boot without persistence and get wifite there, 
everything seems to work just fine.

I must have messed something up somehow I suppose. I'm very much new to Linux 
and apreciate your help. 
```

Original comment by `Kirill.K...@gmail.com` on 9 May 2011 at 10:49

**Comment by GoogleCodeExporter** [comment]
```
Its interesting that the problem only presents itself in persistant mode.  Can 
you provide the output of ls on the file?  
```

Original comment by `bettse@gmail.com` on 10 May 2011 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
I've made some SQL changes, can you try against the latest version?
```

Original comment by `bettse@gmail.com` on 7 Jun 2011 at 12:46

**Comment by GoogleCodeExporter** [comment]
```
Closing since no update in almost 6mo
```

Original comment by `bettse@gmail.com` on 9 Mar 2012 at 10:03
- Changed state: **Fixed**
