### ISSUE TITLE
Name ESSID

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#47]
```
Name ESSID: Tane's_Place

Distributor ID: Ubuntu
Description:    Ubuntu 11.04
Release:    11.04
Codename:   natty



```

Original issue reported on code.google.com by `bum...@googlemail.com` on 16 May 2011 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[+] attacking "Tane's_Place"...
Traceback (most recent call last):
  File "./wifite.py", line 3542, in <module>
    main() # launch the main method
  File "./wifite.py", line 920, in main
    attack(x - 1) # subtract one because arrays start at 0
  File "./wifite.py", line 2005, in attack
    updatesqlstatus('[+] attacking "' + TARGETS[index][8] + '"...')
  File "./wifite.py", line 1382, in updatesqlstatus
    db.execute("""INSERT INTO status (timestamp, status) VALUES (%i, '%s')""" % (time.time(), text))
sqlite3.OperationalError: near "s_Place": syntax error

wifite r81
```

Original comment by `bum...@googlemail.com` on 31 May 2011 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
Sorry for the delay.  I've had trouble with sql sanitization since I don't have 
any ESSIDs in range with apostrophe's to test against.  Please give it a shot 
with r82 and let me know if things are any better, worse, or different.  Thank 
you for your patience
```

Original comment by `bettse@gmail.com` on 1 Jun 2011 at 4:49

**Comment by GoogleCodeExporter** [comment]
```
I believe this is fixed, please verify
```

Original comment by `bettse@gmail.com` on 7 Jun 2011 at 12:47
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I believe this is fixed, please verify
```

Original comment by `bettse@gmail.com` on 7 Jun 2011 at 12:47
