### ISSUE TITLE
Program was working fine until reboot now it fails with this error.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#49]
```
Traceback (most recent call last):
  File "wifite.py", line 3542, in <module>
    main() # launch the main method
  File "wifite.py", line 857, in main
    gettargets()
  File "wifite.py", line 3245, in gettargets
    updatesqlstatus('[+] targeting: ' + ' '.join([TARGETS[x-1][8] for x in ATTACK])) #python list comprehension
  File "wifite.py", line 1382, in updatesqlstatus
    db.execute("INSERT INTO status (timestamp, status) VALUES (%i, '%s')" % (time.time(), text))
sqlite3.OperationalError: near "s": syntax error

this issue is repeated after i did a system reboot
I tried to re install as well with no luck.
```

Original issue reported on code.google.com by `mdcoo...@gmail.com` on 27 May 2011 at 2:57

**Comment by GoogleCodeExporter** [comment]
```
Does it print the list of targets before it crashes?  If so, could you paste 
that list?  I'm wondering if maybe one of the SSIDs in the list caused the SQL 
to become invalid.
```

Original comment by `bettse@gmail.com` on 27 May 2011 at 11:58

**Comment by GoogleCodeExporter** [comment]
```
28 targets and 3 clients found 
[+] targeting:  "CasnerHome" "koop" "Adonis" "SamBeth" "WALLYJOE-PC_Network" 
"Jake2nice" "tommytran" "belkin.5778" "GetYourOwnInternet" "myqwest0002" 
"Bethel's Network" "BTExpress" "Mulgrew" "Blackops" "myqwest6060" 
"Mike_Rosalba" "yesica" "Castille Network" "JasonsPlace" "Internet" 
"myqwest1487" "StewieNet" "McKenna" "victor" "Big Chris" "Belkin.50E4" 
"WORKGROUP" "BigCity"
```

Original comment by `mdcoo...@gmail.com` on 29 May 2011 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
i pasted that up there on the page for you....
I love the program by the way it is awesome...
```

Original comment by `mdcoo...@gmail.com` on 29 May 2011 at 2:20

**Comment by GoogleCodeExporter** [comment]
```
Ah!  I think "Bethel's Network" might have screwed it up.  The apostrophe may 
have prematurely ended the string in the eyes of the SQL statement, thus 
causing an error near the "s" character.  I'll try to find a solution and 
update the code.
```

Original comment by `bettse@gmail.com` on 29 May 2011 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
I've made changes to the sql statements as suggested by some posts I've read 
(One I referenced was 
http://www.velocityreviews.com/forums/t343003-escape-single-and-double-quotes.ht
ml ).  Could you try revision 80 and see if it fixes this crash?
```

Original comment by `bettse@gmail.com` on 29 May 2011 at 7:07

**Comment by GoogleCodeExporter** [comment]
```
i just tried it and still get a crash


] 20 targets and 4 clients found 
[+] targeting:  "Internet" "koop" "Adonis" "SamBeth" "Jake2nice" 
"WALLYJOE-PC_Network" "tommytran" "belkin.5778" "Carl Sommerfeld's Network" 
"Mulgrew" "Mike_Rosalba" "yesica" "GetYourOwnInternet" "crow" "Bethel's 
Network" "Belkin.50E4" "StewieNet" "Nevaeh" "REDNINJA" "myqwest0002" 
Traceback (most recent call last):
  File "wifite.py", line 3542, in <module>
    main() # launch the main method
  File "wifite.py", line 857, in main
    gettargets()
  File "wifite.py", line 3245, in gettargets
    updatesqlstatus('[+] targeting: ' + ' '.join([TARGETS[x-1][8] for x in ATTACK])) #python list comprehension
  File "wifite.py", line 1382, in updatesqlstatus
    db.execute("""INSERT INTO status (timestamp, status) VALUES (%i, '%s')""" % (time.time(), text))
sqlite3.OperationalError: near "s": syntax error

```

Original comment by `mdcoo...@gmail.com` on 31 May 2011 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
This error still occurs version r81
```

Original comment by `bum...@googlemail.com` on 31 May 2011 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
I've continued to have trouble with sql sanitization since I don't have any 
ESSIDs in range with apostrophe's to test against.  Please give it a shot with 
r82 and let me know if things are any better, worse, or different.  Thank you 
for your patience
```

Original comment by `bettse@gmail.com` on 1 Jun 2011 at 4:50

**Comment by GoogleCodeExporter** [comment]
```
sorry it took so long but i have tested it 2 times today and all seems to be 
working fine now... thanks for making changes.. great work!!!
```

Original comment by `mdcoo...@gmail.com` on 6 Jun 2011 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Awesome
```

Original comment by `bettse@gmail.com` on 7 Jun 2011 at 12:43
- Changed state: **Verified**
