### ISSUE TITLE
sqlite3.OperationalError: near "wireless": syntax error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#50]
```
All i did was install backtrack 4r2 and ran the commands in terminal for wifite 
install and got this error when i ran the ./wifite.py

root@bt:~# ./wifite.py

  .;'                     `;,
 .;'  ,;'             `;,  `;,   WiFite r80
.;'  ,;'  ,;'     `;,  `;,  `;,
::   ::   :   ( )   :   ::   ::  mass WEP/WPA cracker
':.  ':.  ':. /_\ ,:'  ,:'  ,:'
 ':.  ':.    /___\    ,:'  ,:'   designed for backtrack4
  ':.       /_____\      ,:'
           /       \

[+] launching gui interface
[+] wireless devices: "wlan0  RTL8187  rtl8187 - [phy0], wlan1  Intel 3945ABG 
iwl3945 - [phy1]"
Traceback (most recent call last):
  File "./wifite.py", line 3542, in <module>
    main() # launch the main method
  File "./wifite.py", line 833, in main
    app = App(root)
  File "./wifite.py", line 275, in __init__
    updatesqlstatus('[+] wireless devices: "' + ', '.join(lst) +'"')
  File "./wifite.py", line 1382, in updatesqlstatus
    db.execute("""INSERT INTO status (timestamp, status) VALUES (%i, %s)""" % (time.time(), text))
sqlite3.OperationalError: near "wireless": syntax error

```

Original issue reported on code.google.com by `Aviles1...@live.com` on 30 May 2011 at 4:37

**Comment by GoogleCodeExporter** [comment]
```
Hey i was messing around with the wifite.py file on line 275 i put a # in front 
of the line and it fixed my problem i dont know what that will cause but only 
time will tell
```

Original comment by `Aviles1...@live.com` on 30 May 2011 at 4:50

**Comment by GoogleCodeExporter** [comment]
```
never mind one i try to run the program it give me way more errors im gonna 
take that # off lol someone please help me
```

Original comment by `Aviles1...@live.com` on 30 May 2011 at 5:04

**Comment by GoogleCodeExporter** [comment]
```
I am also getting this error with a fresh install. I have double checked all of 
the premissions and they seem to be correct on both files and the parent 
directory. Any help would greatly be appreciated.
```

Original comment by `nryo...@gmail.com` on 30 May 2011 at 6:30

**Comment by GoogleCodeExporter** [comment]
```
Sorry for the delay in responding to this.  I'm fairly confident that this is a 
result of the new code I checked in yesterday or the day before.  I made the 
mistake of not testing it properly.  I'm in the process of setting up my test 
environment and I'll try to check in a fix as soon as I find the problem.  
```

Original comment by `bettse@gmail.com` on 30 May 2011 at 10:49

**Comment by GoogleCodeExporter** [comment]
```
I just checked in a fix that readds the single quote marks to the SQL 
statements.  It fixed the same error you were seeing that I saw on my system.  
```

Original comment by `bettse@gmail.com` on 30 May 2011 at 11:05

**Comment by GoogleCodeExporter** [comment]
```
Hey thanks for trying to figure this out but i went to my other computer where 
i installed wifite couple weeks ago and copied the wifite.py executable that 
has the R78 and everything works fine i also did the same in backtrack 5 and 
had no problems accept that bt5 didn't come with pyrit but i figured that out.
```

Original comment by `Aviles1...@live.com` on 31 May 2011 at 6:53

**Comment by GoogleCodeExporter** [comment]
```
Yeah, the versions before SQL were added shouldn't have these problems.  Its 
like one step forward, two steps back.  Part of the trouble with sql 
sanitization is that I don't have any ESSIDs in range with apostrophes to test 
against.  Please give it a shot with r82 and let me know if things are any 
better, worse, or different.  Thank you for your patience
```

Original comment by `bettse@gmail.com` on 1 Jun 2011 at 4:51

**Comment by GoogleCodeExporter** [comment]
```
Bettse,

I ran "./wifite.py -upgrade" to get the newest version and it now works like a 
charm! Thank you so much! Also let me know in the future if you need somebody 
for testing purposes because I would be highly interested. Thanks for your time!
```

Original comment by `nryo...@gmail.com` on 4 Jun 2011 at 11:20

**Comment by GoogleCodeExporter** [comment]
Original comment by `bettse@gmail.com` on 7 Jun 2011 at 12:43
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
Get this error with r84:

Traceback (most recent call last):
  File "wifite.py", line 3542, in <module>
    main() # launch the main method
  File "wifite.py", line 857, in main
    gettargets()
  File "wifite.py", line 3180, in gettargets
    parsetargets()
  File "wifite.py", line 3395, in parsetargets
    if int(temp[7]) == len(temp[8]) and temp[8] != '' and temp[8] != ( chr(0) * len(temp[8])):
ValueError: invalid literal for int() with base 10: 'XN_xxxxxxx_NX'

X was alfa and N was numeric

```

Original comment by `tbb...@gmail.com` on 29 Feb 2012 at 1:45
