### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/tmp/wifiteMLzh00/crackout.tmp' when using pyrit for cracking

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#55]
```
What steps will reproduce the problem?
1. Open xterm and execute this command to use pyrit for the cracking:

python wifite_r82.py -i mon0 -nowep -all -d 
/pentest/passwords/wordlists/wpa.txt -wepw 10 -wpaw 5 -pps 500 xterm --pyrit

2. When the cracking begins an error occurs. 

What is the expected output? What do you see instead?
The expected output should have been that the cracking would have started 
without error.

What version of the product are you using? On what operating system?
I am using wifite version r82 on backtrack 4 R2 in virtualbox 4.1.0 r73009. No 
additional software has been installed except for the  virtual box guest 
additions. The error also occurred with wifite version r68.

Please provide any additional information below.
This is the error i got:

[0:00:01] Cracking;
Traceback (most recent call last):
File "wifite_r82.py", line 3542, in <module>
 main() # launch the main method
File "wifite_r82.py", line 940, in main
 wpa_crack(i)
File "wifite_r82.py", line 1716, in wpa_crack
 wpa_crack_pyrit(index)
File "wifite_r82.py", line 1880, in wpa_crack_pyrit
 f=open(TEMPDIR+'crackout.tmp')
IOError: [Errno 2] No such file or directory: '/tmp/wifiteMLzh00/crackout.tmp'


```

Original issue reported on code.google.com by `kibbelin...@hotmail.com` on 31 Jul 2011 at 9:02

**Comment by GoogleCodeExporter** [comment]
```
The --pyrit command also requires cowpatty to be installed, so double-check to 
make sure you still have it.

What version of Pyrit are you running? 

If you're running on VirtualBox, why would you want to use Pyrit? I thought the 
only advantages of Pyrit are the GPU acceleration, which I don't think you can 
get from a VM. I don't think pyrit would be much faste than the aircrack-ng 
method on VirtualBox.
```

Original comment by `der...@gmail.com` on 3 Aug 2011 at 2:02
