### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#73]
```
Wifite is crashing like this.

[+] launching gui interface
[+] wireless devices: "wlan0  Intel 4965AGN iwl4965 - [phy0], mon0  Intel 
4965AGN iwl4965 - [phy0]"
[+] executing: ./wifite.py -i mon0 -nowpa -console -d none -wepw 0 -wpaw 5 -f 
-anon -pps 500 xterm
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./wifite.py", line 663, in doit
    subprocess.call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1239, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory



What version of the product are you using? On what operating system?
Ubuntu 11.10
WiFite r82
```

Original issue reported on code.google.com by `mxx...@gmail.com` on 27 Jan 2012 at 7:33

**Comment by GoogleCodeExporter** [comment]
```
That looks like a problem with TKinter (maybe). Can you run wifite without the 
GUI? Type:

./wifite.py -console

And let me know if you still get the same error.
```

Original comment by `der...@gmail.com` on 1 Feb 2012 at 10:33

**Comment by GoogleCodeExporter** [comment]
```
I just upgraded to r84.
If I use just console then it doesn't crash. It crashes from GUI.
```

Original comment by `mxx...@gmail.com` on 2 Feb 2012 at 3:44

**Comment by GoogleCodeExporter** [comment]
```
I just tested on 11.10 (via a bootable USB).  The GUI wouldn't load until I 
installed the "tkinter" module for python.

I used apt-get install python-tk to install this module.

I wasn't able to reproduce your error before or after installing tkinter.

Did you install tkinter via apt-get, or some other method?

I wanted to remove dependencies to "macchanger", but they are still in the 
latest revision; do you have macchanger?
```

Original comment by `der...@gmail.com` on 4 Feb 2012 at 10:12

**Comment by GoogleCodeExporter** [comment]
```
I have python-tk and macchanger installed with apt-get
```

Original comment by `mxx...@gmail.com` on 4 Feb 2012 at 10:16
