### ISSUE TITLE
hidden essid bug

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#79]
```
Tryed to attack wep network what has essid hidden, but give me this error. I'm 
using the latest beta v2

   NUM ESSID                 BSSID              CH  ENCR  POWER  WPS?  CLIENT
   --- --------------------  -----------------  --  ----  -----  ----  ------

   17  <Length 5>            00:23:F8:89:EB:30   4  WEP   12db    no   client

 [+] select target numbers (1-17) separated by commas, or 'all': 17

 [+] 1 target selected.

 [1:06:40] preparing attack "" (00:23:F8:89:EB:30)
 [1:06:40] attempting fake authentication (1/5)...           
Traceback (most recent call last):
  File "./wifite2.py", line 2759, in <module>
    main()
  File "./wifite2.py", line 323, in main
    if attack_wep(iface, t, ts_clients):
  File "./wifite2.py", line 2201, in attack_wep
    if wep_fake_auth(iface, target, sec_to_hms(WEP_TIMEOUT)):
  File "./wifite2.py", line 2466, in wep_fake_auth
    proc_fakeauth = Popen(cmd, stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1239, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

Original issue reported on code.google.com by `pta...@gmail.com` on 10 Mar 2012 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
has anyone figured this out im experiencing the same issues
```

Original comment by `ckleinma...@gmail.com` on 10 Sep 2012 at 1:00
