### ISSUE TITLE
Error when running wifite on a headless server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Akash786mrn/wifite#8]
```
What steps will reproduce the problem?
1. Download wifite
2. Run it with --help argument (or any non gui argument)

What is the expected output? What do you see instead?
Expected : List of options

Curently : 

Traceback (most recent call last): 
  File "wifite.py", line 123, in <module> 
    root = Tk() 
  File "/usr/lib/python2.6/lib-tk/Tkinter.py", line 1646, in __init__ 
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use) 
_tkinter.TclError: no display name and no $DISPLAY environment variable 

What version of the product are you using? On what operating system?

REVISION=22

Linux 2.6.32-21-generic #32-Ubuntu SMP Fri Apr 16 08:10:02 UTC 2010 i686 
GNU/Linux
Ubuntu Server 10.04.1 LTS

Please provide any additional information below.
The current server is a Laptop with no X server.


```

Original issue reported on code.google.com by `xionox` on 24 Sep 2010 at 8:04

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
You're talking about executing before X server is started, correct?

I trapped the error. Logged out, ran -help, and didn't receive an error.

Updated in revision 23; please confirm.

Use this to upgrade the script quickly:
./wifite.py -upgrade

```

Original comment by `der...@gmail.com` on 24 Sep 2010 at 8:27
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Use this to upgrade the script quickly:
./wifite.py -upgrade

Need to del/dl the file again because -upgrade shows the error.

Fixed for -help, etc. But running it with no  option display this error :

Traceback (most recent call last): 
  File "wifite.py", line 2823, in <module> 
    main() # launch the main method 
  File "wifite.py", line 688, in main 
    root.title('WiFite GUI') 
NameError: global name 'root' is not defined 

```

Original comment by `xionox` on 24 Sep 2010 at 8:52

**Comment by GoogleCodeExporter** [comment]
```
I think I fixed it in the latest update (revision 24). Tested outside of X and 
it was able to capture a handshake. Please confirm.

Also, thanks a lot for testing.  This really helps me and the other users out a 
lot!
```

Original comment by `der...@gmail.com` on 24 Sep 2010 at 9:05

**Comment by GoogleCodeExporter** [comment]
```
Fixed
```

Original comment by `xionox` on 24 Sep 2010 at 9:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `der...@gmail.com` on 24 Sep 2010 at 11:33
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `der...@gmail.com` on 28 Sep 2010 at 6:45
- Changed state: **Verified**
